import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>MULTI-TOOL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* TODO: ADD NEW FAVICON */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
